default_config = {
    'n_data': 100,
    'sigma_noise': 0.1,
    'datafunction': 'quartic',
    'memory_depth': 2,
    't_phase_ms': 10.0,
    'f_laser_khz': 50.0,
    'det_window_us': 10.0,
    'max_swipe': 21,
    'use_continuous': False,
    'n_swipe': None,
    'swipe_span': 3.14159 / 20,
    'lr': 0.03,
    'epochs': 5,
    'phase_idx': (0, 1),
    'n_photons': (1, 1),
    'init_theta': None,
    'do_plot': True,
    'n_samples': 1000,
    'seed': 42,
    'plotting': 'pyplot',
    'param_save_path': 'model_params.npy',
    'inference_mode': False,
    'use_torch': False
} 