hyperparameter_optimization:
  enabled: False
  steps_range: [2]
  learning_rate_range: [0.01]
  memory_depth_range: [3]
  cutoff_dim_range: [4, 5]

model_comparison:
  enabled: False
  n_samples: [2]

mlp:
  hidden_layers: [64, 64] 
  epochs: 100
  learning_rate: 0.01

polynomial:
  degree: 3

prediction:
  selective_threshold: 0.8
  stochastic: false
  samples: 1
  variance: 0.1

training:
  memory_depth: 5
  cutoff_dim: 4
  steps: 70
  learning_rate: 0.01

data:
  n_data: 200
  sigma_noise_1: 0.1
  datafunction: "quartic_data"